name: risk
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - numpy
  - matplotlib
  - xarray
  - cartopy
  - shapely
  - rapidfuzz
  - netcdf4
  - jupyterlab
  - notebook
  - ipykernel
  - cdo
  - dask
  - scipy
  - pip
